language: objective-c
osx_image: xcode7.2.1
xcode_project: SwiftyProgressBar.xcodeproj
xcode_scheme: SwiftyProgressBar
xcode_sdk: iphonesimulator8.1
script: 'xcodebuild -workspace SwiftyProgressBar.xcodeproj -scheme "SwiftyProgressBar" -destination "platform=iOS Simulator,name=iPhone 6" test'
